### ISSUE TITLE
baidu.py有点问题

### ISSUE THREAD

**Issue by yang2yang** [xiahei/Daily_scripts#5]
1. 如果百度账号，是使用手机号注册，那么可以使用手机号码正常登陆使用，但是如果是用邮箱注册，那么会提示登陆失败。环境：Python 2.7.12    Arch
   可以的话，能回答解惑一下下面几个问题吗？
2. 这个用来检查是否登陆的网址不知道你是怎么找到的？`http://tieba.baidu.com/f/user/json_userinfo`
3. 看了你的博客，你提到密码是明文，但是我自己抓包的时候，发现密码明明被修改成了一长串字符，这个不算加密的过程吗？虽然，从脚本能够正常运行这个角度看，很奇怪呀。
4. 还有有时候baidu登陆会有验证码，但是你的脚本基本上每一次都能够正常登陆，为什么呢？没看到有对验证码的处理呀？不知道是我哪里没有想通吗?
   期待回复。

**Comment by x1ah** [comment]
@yang2yang 
- 我之前试了手机号，用户名登录，能正常登录签到，但是手里没有邮箱注册的号，所以也就没有测试邮箱登录的情况，so sorry。可以的话您可以自己尝试写一个呢。
- 这个返回 json 的站我也具体忘了哪里找的了，检查是否登录成功也可以用别的呢，不一定非要这个，只要用已经`post` 的 `session` 去请求然后判断一下 response 就行了呢。
- 清除浏览器保存的 cookies 再去登录一次，就能发现是明文密码了。
- 也有登录需要验证码的时候，应该是每天有限制, 但是正常使用估计到不了这个次数了吧。
- 这个脚本可能还有一些别的问题，起初只是自己用，并没有太注意这些，所以一些小bug也是在所难免，感谢您的反馈，THX！希望有帮助。

**Comment by yang2yang** [comment]
谢谢回复。我清除cookies之后，又重新试了一下，并没有发现是明文，还是一长串的字符串(加密后？),而且我看你博客上面，虽然把密码给打码了，但是我还是可看到你截的图片也是一长串的字符串(加密后？)。还是我清除cookies的操作有问题？我是直接在地址栏开头的那个东西，然后显示站点信息之后把所有的cookies都remove，应该成功清除了把？但是还是一长串字符串。。。

**Comment by x1ah** [comment]
@yang2yang 
![](http://ww4.sinaimg.cn/large/005NaGmtjw1f5npdse57ej30cn0cajsm.jpg)
![](http://ww4.sinaimg.cn/large/005NaGmtjw1f5npivj39dj30h10l9wi6.jpg)

**Comment by yang2yang** [comment]
谢谢回复，很有帮助。
